// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://isghpsxcyfakccbubqyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzZ2hwc3hjeWZha2NjYnVicXlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwMTQxOTUsImV4cCI6MjA4ODU5MDE5NX0.L484iP1lD0au49wU0h3cUOaH9kuAIN8i2ba323GGqUY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});